---
# Playbook pour exécuter du code PowerShell sur les machines Windows

- name: Exécution de commandes PowerShell sur les machines Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Information de début
      ansible.windows.win_shell: |
        Write-Host "Début de l'exécution sur $(hostname)"
      register: debut

    - name: Afficher le résultat
      debug:
        var: debut.stdout_lines

    # ========================================
    # SECTION À PERSONNALISER
    # Ajoutez votre code PowerShell ici
    # ========================================

    - name: Clean_disk
      ansible.windows.win_shell: |
        $cleanmgr = "cleanmgr.exe"
          $args = "/sagerun:1"
          
          Start-Process -FilePath $cleanmgr -ArgumentList $args -WindowStyle Hidden -Wait
          
          Write-Host "Le nettoyage de disque a été effectué avec succès."

      register: resultat_custom

    - name: Afficher les résultats de votre script
      debug:
        var: resultat_custom.stdout_lines

    # ========================================
    # FIN DE LA SECTION À PERSONNALISER
    # ========================================

    - name: Information de fin
      ansible.windows.win_shell: |
        Write-Host "Fin de l'exécution sur $(hostname)"
      register: fin

    - name: Afficher le message de fin
      debug:
        var: fin.stdout_lines
