---
# Playbook pour exécuter du code PowerShell sur les machines Windows

- name: Exécution de commandes PowerShell sur les machines Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Information de début
      ansible.windows.win_shell: |
        Write-Host "Début de l'exécution sur $(hostname)"
      register: debut

    - name: Afficher le résultat
      debug:
        var: debut.stdout_lines

    # ========================================
    # SECTION À PERSONNALISER
    # Ajoutez votre code PowerShell ici
    # ========================================

    - name: Clean_Profiles_CAMPUS
      ansible.windows.win_shell: |
        # Script PowerShell 64 bits - Supprime les profils locaux issus du domaine "CAMPUS"
          # À exécuter en tant qu'administrateur

          # Remplace cette valeur par le SID racine trouvé à l'étape précédente
          $DomainSID = "S-1-5-21-495494928-1333678342-1936946330"

          Get-CimInstance Win32_UserProfile | Where-Object {
              $_.SID -like "$DomainSID-*" -and -not $_.Special -and -not $_.Loaded
          } | ForEach-Object {
              try {
                  $_ | Remove-CimInstance
                  Write-Host "Profil supprimé : $($_.LocalPath) ($($_.SID))" -ForegroundColor Green
              } catch {
                  Write-Warning "Impossible de supprimer le profil : $($_.LocalPath) ($($_.SID)) - $($_.Exception.Message)"
              }
          }

      register: resultat_custom

    - name: Afficher les résultats de votre script
      debug:
        var: resultat_custom.stdout_lines

    # ========================================
    # FIN DE LA SECTION À PERSONNALISER
    # ========================================

    - name: Information de fin
      ansible.windows.win_shell: |
        Write-Host "Fin de l'exécution sur $(hostname)"
      register: fin

    - name: Afficher le message de fin
      debug:
        var: fin.stdout_lines
