---
- name: Mettre à jour et éteindre une machine Windows
  hosts: all
  gather_facts: yes
  tasks:
    - name: Installer toutes les mises à jour Windows
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        reboot: yes         # Redémarrage automatique si besoin
        state: installed

    - name: S'assurer que toutes les mises à jour sont bien appliquées et que le système est stable
      win_reboot:
        reboot_timeout: 600
      when: ansible_reboot_required | default(false)

    - name: Arrêter proprement la machine une fois les mises à jour terminées
      win_shell: 'Stop-Computer -Force'
