---
# Playbook pour exécuter du code PowerShell sur les machines Windows

- name: Exécution de commandes PowerShell sur les machines Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Information de début
      ansible.windows.win_shell: |
        Write-Host "Début de l'exécution sur $(hostname)"
      register: debut

    - name: Afficher le résultat
      debug:
        var: debut.stdout_lines

    # ========================================
    # SECTION À PERSONNALISER
    # Ajoutez votre code PowerShell ici
    # ========================================

    - name: Exécuter votre code PowerShell personnalisé
      ansible.windows.win_shell: |
        # Script PowerShell 64 bits corrigé pour installation silencieuse MATLAB 2024b
        $setupPath = "C:\install\setup.exe"
        $configPath = "C:\install\installer_input.txt"

        # Correction de la condition avec parenthèses autour de chaque Test-Path
        if ((Test-Path $setupPath) -and (Test-Path $configPath)) {
            # Ajout des guillemets échappés pour les chemins avec espaces
            Start-Process -FilePath $setupPath -ArgumentList "-inputFile `"$configPath`"" -Wait
        } else {
            Write-Error "Fichiers d'installation manquants"
        }

      register: resultat_custom

    - name: Afficher les résultats de votre script
      debug:
        var: resultat_custom.stdout_lines

    # ========================================
    # FIN DE LA SECTION À PERSONNALISER
    # ========================================

    - name: Information de fin
      ansible.windows.win_shell: |
        Write-Host "Fin de l'exécution sur $(hostname)"
      register: fin

    - name: Afficher le message de fin
      debug:
        var: fin.stdout_lines
