---
# Playbook pour exécuter du code PowerShell sur les machines Windows

- name: Exécution de commandes PowerShell sur les machines Windows
  hosts: all
  gather_facts: yes

  tasks:
    - name: Information de début
      ansible.windows.win_shell: |
        Write-Host "Début de l'exécution sur $(hostname)"
      register: debut

    - name: Afficher le résultat
      debug:
        var: debut.stdout_lines

    # ========================================
    # SECTION À PERSONNALISER
    # Ajoutez votre code PowerShell ici
    # ========================================

    - name: Exécuter votre code PowerShell personnalisé
      ansible.windows.win_shell: |
        $matlabRoot = "C:\Program Files\MATLAB\R2022b"
        $uninstallExe = "$matlabRoot\uninstall\bin\win64\uninstall.exe"
        $tempFolder = "C:\temp"
        $inputFile = "$tempFolder\my_uninstall.txt"

        # Créer le dossier temporaire s'il n'existe pas
        if (-not (Test-Path -Path $tempFolder -PathType Container)) {
            New-Item -Path $tempFolder -ItemType Directory -Force
        }

        # Copier le fichier de configuration
        Copy-Item "$matlabRoot\uninstall\uninstaller_input.txt" $inputFile -Force

        # Modifier le fichier de configuration
        Set-Content -Path $inputFile -Value @"
        mode=silent
        outputFile=$tempFolder\matlab_uninstall.log
        "@

        # Lancer la désinstallation silencieuse
        Start-Process -FilePath $uninstallExe -ArgumentList "-inputFile $inputFile" -Wait

        # Nettoyage final
        Start-Sleep -Seconds 5
        if (Test-Path $matlabRoot) {
            Remove-Item -Path $matlabRoot -Recurse -Force -ErrorAction SilentlyContinue
        }

      register: resultat_custom

    - name: Afficher les résultats de votre script
      debug:
        var: resultat_custom.stdout_lines

    # ========================================
    # FIN DE LA SECTION À PERSONNALISER
    # ========================================

    - name: Information de fin
      ansible.windows.win_shell: |
        Write-Host "Fin de l'exécution sur $(hostname)"
      register: fin

    - name: Afficher le message de fin
      debug:
        var: fin.stdout_lines
